### ISSUE TITLE
Whats the best config for mixed apps with /metrics and /actuator/prometheus

### ISSUE THREAD

**Issue by jensbaitingerbosch** [promregator/promregator#178]
We have several apps running. Some are written with Spring Boot exposing thir metrics at `/actuator/prometheus` and some apps expose their metrics at `/metrics`. I tried to have a minimal configuration, so promregator tries both endpoints

```
promregator:
  targets:
    - orgName: myOrg
      path: /metrics
    - orgName: myOrg
      path: /actuator/prometheus
```

but this results in a) all apps doubled in the discovery (one for each metrics endpoint) and also many failed scrapes (all apps that expose at `/metrics` fail when scaped at `/actuator/prometheus` and vice versa). 

I could configure which app exposes the app its metric at which endpoint, but this would mean effort to maintain this config, with my deployments. 

```
promregator:
  targets:
    - orgName: myOrg
      applicationRegex: (app1)|(app2)
      path: /metrics
    - orgName: myOrg
      applicationRegex: (app3)|(app4)
      path: /actuator/prometheus
```

My currently prefered solution would be to change all Spring apps so all apps expose their metrics at `/metrics`. 

Or is thera another configuration option I could use?

There are some Ideas that I had, but I don't like: 
- have a prefix at the appname depenaing on where they expose the metrics: unhandy and errorprune {when someone deploys an app without the prefix it will not work):
  ```
  promregator:
    targets:
      - orgName: myOrg
        applicationRegex: non-spring-app.*
        path: /metrics
      - orgName: myOrg
        applicationRegex: spring-app.*
        path: /actuator/prometheus
  ```
- change Promregator so it probes potential metric endpoints, caches them for the app and then scrapes from the working endpoint. Sounds nice, but the edgecases are the problems and lead to undefined situations:
  - More then one endpoints work and potentially produces different metrics, which should be scraped
  - None of endpoints work (http status 4xx, 5xx or any low level issue): Is this intensionally (maybe because the app simply does not expose metrics) or is the app somehow down/broken that it cannot produce metrics and should be considered as not UP. Which errors get higher prio? e.g. one endpoint produces a 404, the other a 401, could mean that one endpoint does not exist and for the other one 'only' the authentication did not work...

**Comment by checketts** [comment]
For now you best option is your second one: using several applicationRegex entries.

Eventually I would like to support the new [metadata](https://docs.cloudfoundry.org/adminguide/metadata.html) options so an application could include in its manifest where it exposes its metrics endpoint:

```
<manifest snippet>
metadata:
  annotations:
    prometheusEndpoint: /actuator/prometheus
```

This option doesn't exist yet.
