### ISSUE TITLE
Application fails to start when getting UAA Authentication Token

### ISSUE THREAD

**Issue by dmfrey** [promregator/promregator#182]
## Environment
PCF 2.6
Promregator versions tried; 0.7.5, 0.7.6, 0.8.0-rc2
Java 11

## Summary / Problem Statement
Application will not start. Seems to be an issue getting a null token from UAA Authentication Provider. See attached stacktrace
[promregator_stacktract.txt](https://github.com/promregator/promregator/files/4717951/promregator_stacktract.txt)

## Observed Behavior
Application does not start

## Expected Behavior
Application should start.

**Comment by checketts** [comment]
I was able to reproduce this error by providing an incorrect username or password. Can you please double check that there aren't any unexpected characters and that the credentials provided are correct?

**Comment by dmfrey** [comment]
@checketts  are there specific permissions required to call that api?

**Comment by eaglerainbow** [comment]
> are there specific permissions required to call that api?

Not really.
AFAIK you just need to be able to logon...
You even don't need to be authorized for any org/space or so.

**Comment by eaglerainbow** [comment]
I am also currently checking, if we can improve the error message in general, but from what I also see, I would assume that it's some sort of logon failure that you are getting...

**Comment by eaglerainbow** [comment]
Ugly like hell! The exception which is thrown is nested twice and marked as `private`: https://github.com/cloudfoundry/cf-java-client/blob/272094ceca9c54b7ccf125adf80d5be044a4f73b/cloudfoundry-client-reactor/src/main/java/org/cloudfoundry/reactor/util/Operator.java#L233

You could only hard-code the name of the class; and the contents of the properties is nil:
![grafik](https://user-images.githubusercontent.com/12811079/83559920-a76c2480-a515-11ea-93b5-22290c0a9b3e.png)
🤮

**Comment by eaglerainbow** [comment]
You also get the very same strange exception even if you call

```java
Mono<String> tokenMono = this.cloudFoundryClient.getTokenProvider().getToken(this.cloudFoundryClient.getConnectionContext());
tokenMono.block();
```

I wonder how providing a proper error message here is thought to be done by applications in first place.

**Comment by eaglerainbow** [comment]
On the approach of improving support for invalid credentials provided I have raised https://github.com/cloudfoundry/cf-java-client/issues/1046. 
Perhaps I have overlooked something.

**Comment by eaglerainbow** [comment]
@dmfrey  Currently I don't see any chance to improve the error message (e.g. providing detailed information about what exactly went wrong). It looks like we have to wait for https://github.com/cloudfoundry/cf-java-client/issues/1046. Yet, like @checketts  I am rather confident that this has "something to do" with your username/password authentication towards the CF platform. 
That is why I also would like to kindly ask you to double-check your configuration in that regard (missing escaping of special characters in the password - or something like this).

**Comment by eaglerainbow** [comment]
Note: I tried also to get hex dump debugging running for netty, but failed to get what I wanted to see.

**Comment by dmfrey** [comment]
I had the platform team create me a user with SPACE_DEVELOPER. I'm wondering if that privilege is not enough to call the cf API? The username and password are just set in the manifest right now until we iron this out as `CF_USERNAME` and `CF_PASSWORD`

**Comment by dmfrey** [comment]
password does have `!!` in it, but I don't see anything else that would be a special character

**Comment by eaglerainbow** [comment]
> The username and password are just set in the manifest right now until we iron this out as CF_USERNAME and CF_PASSWORD

Do I get you right that with setting it in manifest.yaml it worked?

> password does have `!!` in it, but I don't see anything else that would be a special character

How did you set it? With Bash's double quotes or with single quotes?

**Comment by eaglerainbow** [comment]
Are you aware of https://stackoverflow.com/a/24980706 ?

**Comment by dmfrey** [comment]
No, it doesn't work by just setting it in manifest.yml.

I didn't have quotes around it, but am adding them now

**Comment by checketts** [comment]
YAML needs [quoting with some special characters](https://support.asg.com/mob/mvw/10_0/mv_ag/using_quotes_with_yaml_special_characters.htm). I hope that helps it

**Comment by dmfrey** [comment]
```
---
applications:
- name: promregator-acceptance
  path: promregator-0.7.6.jar
   buildpacks:
     - java_buildpack_offline
  env:
    JBP_CONFIG_OPEN_JDK_JRE: "{ jre: { version: 11.+}}"
    PROMREGATOR_TARGETS_0_PROTOCOL: https
    PROMREGATOR_TARGETS_0_ORG_NAME: [ORG]
    PROMREGATOR_TARGETS_0_PATH: /actuator/prometheus
    PROMREGATOR_TARGETS_0_SPACE_NAME: acceptance
    PROMREGATOR_TARGETS_0_APPLICATION_NAME: [APP NAME]
    CF_API_HOST: [A VALID API HOST]
    CF_USERNAME: '[A VALID EMAIL]'
    CF_PASSWORD: '[PASSWORD WITH !! IN IT]'
    CF_SKIP_SSL_VALIDATION: true
    LOGGING_LEVEL_JAVA_ORG_CLOUDFOUNDRY_PROMREGATOR: DEBUG
    LOGGING_LEVEL_ORG_CLOUDFOUNDRY: DEBUG
```
See anything out of the ordinary? It's been redacted to protect the innocent ;)
