### ISSUE TITLE
0.8.0 - Too many open files

### ISSUE THREAD

**Issue by dsg-anthony** [promregator/promregator#188]
## Environment
Promregator 0.8.0
Cent OS 7
delivered jar 

## Summary / Problem Statement
File descriptors grow until promregator crashes.
java.io.IOException: Too many open files

## Observed Behavior
![image](https://user-images.githubusercontent.com/43544235/98894906-d8149a80-2473-11eb-94fc-271fd999bd5c.png)

```yaml
---
server:
  port: 50001
cf:
  api_host: ${promregator.url}
  username: ${promregator.username}
  password: ${promregator.password}
  cache.type: CAFFEINE
  connectionPool:
    size: 32
logging:
  level:
    org:
      cloudfoundry:
        promregator: ERROR
promregator:
  scraping:
    threads: 14
  authenticator:
    type: none
```
