### ISSUE TITLE
Promregator running in PCF - Issues with /discovery - promregator.discovery.port

### ISSUE THREAD

**Issue by WilliamLHarms** [promregator/promregator#189]
## Environment
Implementation-Title: Promregator
Implementation-Version: 0.8.0

Running promregator within PCF PAS 2.8

From the prometheus node, doing a simple wget on a cron to build a discovery file.  
## Summary / Problem Statement
The discovery endpoint has a port, 8080 in the config.  When trying to curl to the https://route:8080/singleTargetMetrics/guids/instance, I get a cert error:
curl: (35) SSL received a record that exceeded the maximum permissible length.

When I try to browse there I receive:  ERR_SSL_PROTOCOL_ERROR

When I try to browse to the discovery route without the port, everything works fine.  

I am also reaching out to our PCF Platform team to see if something can be done on their side to help open the port.

Documents I consulted: 
https://github.com/promregator/promregator/blob/master/docs/config.md#option-promregatordiscoveryport-optional

Code I reviewed:
https://github.com/promregator/promregator/blob/bf0e2ac0b33065f474e257a872f8f03202f8defa/src/main/java/org/cloudfoundry/promregator/endpoint/DiscoveryEndpoint.java#L141

^^^ doesn't look like we can turn that off...   Thoughts on adding an additional property that will enable the default port to be off in the targets string?  My other option is to write a post process from the wget that will yank the port out of the file.

## Observed Behavior
Running the following cf push manifest:

```yaml
---
applications:
- name: promregator
  path: promregator.jar
  memory: 1g
  instances: 1
  env:
    JAVA_OPTS: '-Dspring.config.location=file:$PWD/promregator.yml'
    SKIPVERIFY: true
    spring.application.name: promregator
```

With this promregator yaml config:
```yaml
server:
  port: 50082
cf:
  api_host: api.sys.ap01.pcf.company.com
  username: SECRET
  password: SECRET
  cache.type: CAFFEINE
  cache.timeout.application: 600
  connectionPool:
    size: 32
  request.timeout.appSummary: 6000
  request.timeout.appInSpace: 3000
logging:
  level:
    org:
      cloudfoundry:
        promregator: ERROR
promregator:
  scraping:
    threads: 14
  authenticator:
    type: none
  discovery:
    hostname: promregator.apps.ap01.pcf.company.com
  targets:
```

Tomcat looks good:  o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat started on port(s): 8080 (http) with context path ''

Yields this discovery json.. Note the port... 
```json
{
"targets": [
"promregator.apps.ap01.pcf.company.com:8080"
],
"labels": {
"__meta_promregator_target_path": "/singleTargetMetrics/xxxxx-yyyy-zzzz-9999-888888888/0",
"__meta_promregator_target_orgName": "some-org",
"__meta_promregator_target_spaceName": "some-space",
"__meta_promregator_target_applicationName": "some-app",
"__meta_promregator_target_applicationId": "xxxxx-yyyy-zzzz-9999-888888888",
"__meta_promregator_target_instanceNumber": "0",
"__meta_promregator_target_instanceId": "xxxxx-yyyy-zzzz-9999-888888888:0",
"__metrics_path__": "/singleTargetMetrics/xxxxx-yyyy-zzzz-9999-888888888/0"
}
}
```

When I curl from the prometheus box to the singleTargetMetrics route, nothing works.  When I take the port off I'm good.

## Expected Behavior
The ability to remove a port reference from the promregator on discovery.

fyi - @eaglerainbow
