### ISSUE TITLE
Document new Prometheus HTTP Service Discovery

### ISSUE THREAD

**Issue by checketts** [promregator/promregator#201]
Prometheus now supports HTTP based service discovery: https://prometheus.io/docs/instrumenting/http_sd/

I'll do a spike on leveraging it and that adding documentation for how to leverage it with Promregator. Will also be checking if we need to change the returned format to support it.

**Comment by pakita** [comment]
Hi , may be I am missing something but the latest release is still 2.27.1/2021-05-18
https://github.com/prometheus/prometheus/releases
Please can you point me to the right direction where I can find 2.28?
Thank you

**Comment by checketts** [comment]
I noted the version since it hasn't been released yet. The feature was just added this week

**Comment by checketts** [comment]
Release candidate now available: https://github.com/prometheus/prometheus/releases/tag/v2.28.0-rc.0

**Comment by checketts** [comment]
It was a breeze to use:

```
  - job_name: "promregator"
    scheme: https
    http_sd_configs:
      - url: https://<promregator url>/v2/discovery
        
    relabel_configs:
     - source_labels: [__meta_promregator_target_applicationName,__meta_promregator_target_instanceNumber]
       target_label: instance
       separator: "-"
     - source_labels: [__meta_promregator_target_orgName]
       target_label: org_name
     - source_labels: [__meta_promregator_target_spaceName]
       target_label: space_name
     - source_labels: [__meta_promregator_target_applicationName]
       target_label: application
     - source_labels: [__meta_promregator_target_api]
       target_label: api
```

I'll get a PR created that documents this a the new preferred way.
