### ISSUE TITLE
Using 'true' (without quotes) is problematic when using prometheus.io/scrape annotation

### ISSUE THREAD

**Issue by checketts** [promregator/promregator#211]
To use annotations in a manifest you might try:

```yaml
applications:
- name: my-app
  path:      app.jar
  buildpack: java11
  metadata:
    annotations:
      prometheus.io/scrape: true
      prometheus.io/path: actuator/prometheus
```

However this reveals an annoying yaml 'feature', the value `true` is converted to a boolean. The result is that `cf push` fails with an unhelpful 500. The secret is to quote the true value:

```yaml
applications:
- name: my-app
  path:      app.jar
  buildpack: java11
  metadata:
    annotations:
      prometheus.io/scrape: "true" //Note the double quotes
      prometheus.io/path: actuator/prometheus
```

Perhaps a different value than "true" could be used?

@braunsonm do you have any recommendations or ideas? 

Options: (that can be supported in addition to 'true')
- enabled
- anything other than false?

Also is there a reason that annotations were chosen instead of labels? (Since labels are intended for selecting resources)
