### ISSUE TITLE
Enhancement for using Promregator in a zero trust environment with ORY OathKeeper

### ISSUE THREAD

**Issue by sfrevel** [promregator/promregator#215]
## Environment
* Promregator 0.10.0
* Cloudfoundry api 3.102.0
* OathKeeper 0.38

## Summary / Problem Statement
A couple of spring  boot services are deployed on cloudfoundry and the routes are protected with ORY OathKeeper. So for accessing an endpoint you have to get a OAuth2 token for accessing the route to Oathkeeper, Oathkeeper then delegates the call to the internal route from the service with a newly issued second OAuth2 token. This is also the case for the metrics endpoints which are prefixed in the Oathkeeper route config to separate the service endpoints.

So if Promregator is used, Promregator has to access the route provided by Oathkeeper one the one hand, but also need to retrieve the 'metadata' via the cloudfoundry api on the other hand. Except that the route which is retrieved by cloudfoundry api along with the metadata could not be used, because it's not accessible while protected with Oathkeeper. So something like an explicitAccessUrl is needed to configure the route to Oathkeeper along with the target, and 'overwrite' the route retrieved with the metadata.

like this

```
  targets:
    - orgName: myorg
      spaceName: myspace
      applicationName: 'myapplicationname'
      path: '/service-prefix/actuator/prometheus'
      explicitAccessUrl: 'my.api.via.oathkeeper.com'
```
## Observed Behavior
Without the enhancement the selected internal route is used where you get an HTTP 401 because the route is accessed directly and not with the token issued by OathKeeper

## Expected Behavior
The explicit access url should be used and therefore the access to the internal route, which is configured in this case by OathKeeper, is done with the token issued by OathKeeper.

We do have a fork with an implementation for doing exactly this and would like to contribute this in the case someone else has such an environment or a similar situation.

**Comment by checketts** [comment]
Yes, please provide a PR so we can see the needed enhancements.

**Comment by eaglerainbow** [comment]
I am not into OathKeeper, but your approach sounds rather reasonable to me.
I am also a little curious about the use case: Is the XSUAAOAuth2 Authenticator sufficient for your case - or is there more to the authentication procedure using OathKeeper?
Would it make sense to provide documentation, e.g. in form of an example configuration how you made things fly?

**Comment by eaglerainbow** [comment]
@checketts I would be in general fine with the proposal there (modulo the naming of the configuration attribute). I could also imagine also further cases where overwriting the access URL for the metrics might be helpful. So, this sounds like a good idea to me. 

What are your thoughts on this?

**Comment by eaglerainbow** [comment]
BTW: Greetings to my near south at Echterdingen...

**Comment by checketts** [comment]
I'm also not familiar with OathKeeper. It looks like you don't need OathKeeper to be included as an AuthenticationEnricher?

I like the idea and also agree that overwriting the URL is actually simpler for a new user (instead of balancing route and path, just providing a specific URL).

I would like to add the ability to set this via annotations as well (I'll contribute this as an update to the 'v2 lite' branch)

**Comment by eaglerainbow** [comment]
> I'm also not familiar with OathKeeper. It looks like you don't need OathKeeper to be included as an AuthenticationEnricher?

Another reason for my ask on documentation 😀 
We are seeking to understand the integration part for this use case of Promregator.

**Comment by sfrevel** [comment]
> I am not into OathKeeper, but your approach sounds rather reasonable to me. I am also a little curious about the use case: Is the XSUAAOAuth2 AuthenticationEnricher sufficient for your case - or is there more to the authentication procedure using OathKeeper? Would it make sense to provide documentation, e.g. in form of an example configuration how you made things fly?

From our perspective the XSUAAOATH2 AuthenticationEnricher configured like this
```
cf:
  api_host: api-host
  username: api-user
  password: api-passwort
  skipSslValidation: true

promregator:
  authenticator:
    type: oauth2xsuaaBasic
    oauth2xsuaaBasic:
      tokenServiceURL: https://tokenServiceUrl/oauth/token
      client_id: client-id
      client_secret: client-secret
``` 

was sufficient. 

Concerning the documentation for the setup - I suppose you have something in you mind where the example describe how OathKeeper and Promregator are tied together? I think for Promregator it should be clear with the config snippet above - This is enough for getting the token for the Oathkeeper access. For OathKeeper config I have to talk to my colleagues, because I just configured the metrics endpoints of the services in the OathKeeper config. Or Do you need an example for such an metrics endpoint config?
