### ISSUE TITLE
Scrape from multiple CF endpoints / CF platforms

### ISSUE THREAD

**Issue by eloo** [promregator/promregator#58]
Hi,
we've currently figured out that with the current implemenation only one CF endpoint can be used.
But in our case we want to monitor apps from two different CFs.
So what do you guys think about that? Maybe the config can be changed to support somethink like this:

```
cf:
      - api-host: ...
         targets: ...
      - api-host: ....
         targets: ...
```
or maybe give an api-host an identifier and use the identifier in the targets?

Thanks
Eloo
