### ISSUE TITLE
Yaml issues in documentation

### ISSUE THREAD

**Issue by eloo** [promregator/promregator#68]
Hi,
im at the moment trying the targetAuth configuration and found an issue in the documentation.
https://github.com/promregator/promregator/blob/master/docs/outbound-authentication.md
the Yaml example there is invalid
```
 targetAuthenticators:
   - id: targetAuthenticator1
     type: basic
       username: targetUsername
       password: targetPassword

   - id: targetAuthenticatorNull
     type: null
```

the indention of username and password is wrong.. i guess it should be aligned with id and type?

thx

**Comment by eloo** [comment]
a looks like it should be 
```
 targetAuthenticators:
   - id: targetAuthenticator1
     type: basic
     basic:
       username: targetUsername
       password: targetPassword

   - id: targetAuthenticatorNull
     type: null
```
