### ISSUE TITLE
Performance: Many App calls (whilst SpaceSummary could also do the trick)

### ISSUE THREAD

**Issue by eloo** [promregator/promregator#74]
Hi,
related to #67 we have started to monitor promregator a little bit and we found some interesting statistics.
For example the huge amout of App calls
We are facing for example the following distribution of calls:
```
promregator_cffetch_latency_count{request_type="allApps"}  | 48168
promregator_cffetch_latency_count{request_type="app"}  | 714556
promregator_cffetch_latency_count{request_type="org"} | 14
promregator_cffetch_latency_count{request_type="space"}  | 84
promregator_cffetch_latency_count{request_type="spaceSummary"} | 146410
```
We have the following cache timout settings:
```
  cache:
    timeout:
      org: 86400        # Renew org cache every day (default: 3600)
      space: 43200      # Renew space cache twice a day (default: 3600)
      application: 15   # Renew app cache every 15s (default: 300)
      resolver:  60     # Renew target to CF (e.g. AllApps or regex) (default: 300)
```
With 18 Apps and 30 Instances monitored covered over a time of ~14 days.
We have a average of 35-40 app calls per minute.

So now the question:
For me this looks like a very huge amount of app requests and for me it looks like we are not gathering "new" information from the app call itself. 
So is it really neccessary to have that much app calls? because for me it looks like the space Summary is also containing all the needed data? 

Maybe @eaglerainbow you can give some insight?

Thx
