### ISSUE TITLE
Inconsistent Case for App Name in Discovery

### ISSUE THREAD

**Issue by eaglerainbow** [promregator/promregator#77]
## Environment
Promregator v0.5.0-rc5

## Summary / Problem Statement
The case of the application name may be different if discovered using `applicationRegex` compared `applicationName`

## Observed Behavior
Let there be an application called "testApp" in a space that we want to discover. The target configuration

```yaml
  targets:
    - orgName: org
      spaceName: space
      applicationName: testapp
```
will result in a discovery where the application is called `testapp` (like in the configuration). 

The configuration
```yaml
  targets:
    - orgName: org
      spaceName: space
      applicationRegex: testapp
```
(mind that we run over regexing now) results in an application called `testApp`. 

This is inconsistent.

## Expected Behavior
In both cases, the application shall be called `testApp`.
