### ISSUE TITLE
cf.skipSslValidation not working

### ISSUE THREAD

**Issue by ntrip** [promregator/promregator#79]
Hi Team,

**Problem Statement:**

I am trying to run Promregator basic setup by following this:
https://github.com/promregator/promregator/blob/master/docs/quickstart-docker.md

but I am getting below error
`Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

I got cf.skipSslValidation config https://github.com/promregator/promregator/blob/master/docs/config.md which I think I should set, but I couldn't set it properly. I have tried multiple values for skipSslValidation in the promregator.yml file but getting same error:

```
cf:
  api_host: api.cf.example.org
  username: myCFUserName
  skipSslValidation: true / TRUE / enable / ENABLE / none / NONE / yes / YES
```

**Environment:**
Promregator Application v0.1.0 
OS: Ubuntu 18.04 VM

**Below are my questions:**
1) How can I skip the SSL validation for Promregator demo purpose?
2) If I have the SSL Key file then where should I add it in Ubuntu 18.04? I have tried to put my key in this file /etc/ssl/certs/ca-certificates.crt but got the same error.

Thanks in advance!

Regards,
Neetu
