### ISSUE TITLE
Configured target where application id cannot be retrieved leads to Discovery error

### ISSUE THREAD

**Issue by eaglerainbow** [promregator/promregator#86]
## Environment
promregator in docker 0.6.0-SNAPSHOT

## Observed Behavior
If a `spaceRegex` is configured to include an empty space, the request for retrieving the applicationId fails the entire request and no discovery is performed for the rest of spaces.

## Expected Behavior
The discovery is continued with the next possible space.

## Example Configuration
```yaml
  targets:
    - orgName: someOrg
      spaceRegex: .*
      applicationName: testapp
      path: /metrics
```
