### ISSUE TITLE
define the scrape endpoint per application name.

### ISSUE THREAD

**Issue by thestevenbell** [promregator/promregator#97]
## Environment
*describe the environment: *
- Docker image: promregator/promregator:0.5.7
- Cloud Foundry platform API version: 2.112.0)

## Summary / Problem Statement
Unable to assign a specific metrics endpoint for each application defined in the <targets> section.  

## Observed Behavior
All application instances must have the same endpoint to be scraped by Promregator.

## Expected Behavior
Rather, it would be helpful to be able to define the scrape endpoint per application name.

For example:
  ```
targets:
     - orgName: Inventory
       spaceName: QA
       - applicationName: on-hold
          path: '/metrics'
       - applicationName: sold
          path: '/actuator/prometheus'
```

**Comment by eaglerainbow** [comment]
Hi,
Thanks for reporting your issue.
Unfortunately, I don't really get the point you have. I think you can provide an individual path for each application scraped. In your example, this would look something like this:

```
targets:
     - orgName: xyz
       spaceName: QA
       applicationName: on-hold
       path: '/metrics'
    - orgName: xyz
      spaceName: QA
      applicationName: sold
      path: '/actuator/prometheus'
``` 
see also https://github.com/promregator/promregator/blob/989ab736eda71b77773ed37ec6e196fa211e2865/docs/config.md section on `promregator.targets[]` there.

Or do I miss the point you want to make?

**Comment by thestevenbell** [comment]
The current documentation does explain the correct.  I misinterpreted. 

If the use is changed to `promregator.targets[].applicationName[]` this would reduce repetition needed to define the Org and Spaces when the Orgs and Spaces have many applications.

**Comment by eaglerainbow** [comment]
> If the use is changed to promregator.targets[].applicationName[] this would reduce repetition needed to define the Org and Spaces when the Orgs and Spaces have many applications.

I would take this as a suggestion for enhancement.
That is why I'll adjust the description of this issue accordingly.

**Comment by eaglerainbow** [comment]
Note that 
```yaml
targets:
     - orgName: Inventory
       spaceName: QA
       - applicationName: on-hold
         path: '/metrics'
       - applicationName: sold
         path: '/actuator/prometheus'
``` 
isn't valid yaml. Only
```
targets:
     - orgName: Inventory
       spaceName: QA
       applications:
       - applicationName: on-hold
         path: '/metrics'
       - applicationName: sold
         path: '/actuator/prometheus'
```
would be.

**Comment by eaglerainbow** [comment]
If we did this `applications` approach, the following attributes would also have to be set on application level:
* path
* protocol
* preferredRouteRegex

**Comment by eaglerainbow** [comment]
@eloo: What's your opinion (out of experience from practice) on a configuration approach something like this:
```yaml
targets:
     - orgName: Inventory
       spaceName: QA
       applications:
       - applicationName: on-hold
         path: '/metrics'
       - applicationName: sold
         path: '/actuator/prometheus'
```

Would this `applications` approach simplify / make the configuration more readable for you?

**Comment by eaglerainbow** [comment]
We have an additional boundary condition which we still have to keep:
We must stay compatible to the old way of configuration. So

```yaml
targets:
    - orgName: xyz
      spaceName: QA
      applicationName: on-hold
      path: '/metrics'
    - orgName: xyz
      spaceName: QA
      applicationName: sold
      path: '/actuator/prometheus'
``` 
still must work.

**Comment by eaglerainbow** [comment]
Also keep in mind that
```yaml
targets:
    - applicationName: on-hold
      path: '/metrics'
``` 
also is a valid target today (and would mean "all applications called 'on-hold' in any space or org").

The same also applies to
```yaml
targets:
    - orgName: org1 
      path: '/metrics'
``` 
which would mean "in org 'org1' all applications in all spaces".

**Comment by eaglerainbow** [comment]
To keep compatibility, this would mean that
```yaml
targets:
    - applications: 
       - app1
       - app2
``` 
would mean "applications named 'app1' or 'app2' in any org and any space".

That's freaky. 😵
